/* This code is part of WoT, a plugin for Freenet. It is distributed
 * under the GNU General Public License, version 2 (or at your option
 * any later version). See http://www.gnu.org/ for details of the GPL.
 *
 * The nameparts are compiled from names of (often long) deceased
 * scientists found in Wikipedia. Names themselves can not be
 * copyrighted and the level needed for copyrighting a list is not
 * reached (reply from Wikipedia supporters), so the list of names can
 * be used freely(1). Thus we have the right to use it under GPL (though
 * this does not protect the selection of names).
 *
 * (1) http://de.wikipedia.org/w/index.php?title=Hilfe:FAQ_Rechtliches&oldid=94743640#Darf_ich_Tabellen.2C_Listen_oder_statistische_Daten_.C3.BCbernehmen.3F
 */

/** Create a random name from a list of names of scientists. **/

package plugins.WebOfTrust.util;

import static java.lang.Math.max;
import static java.lang.Math.min;
import static java.lang.System.out;

import java.util.Random;

import freenet.l10n.ISO639_3;
import plugins.WebOfTrust.Identity;
import plugins.WebOfTrust.exceptions.InvalidParameterException;

public final class RandomName {

	/** For development purposes.
	 * 
	 *  Prints info about the set of template {@link #firstnames} and {@link #lastnames} which we
	 *  use as foundation to generate random names.
	 *  
	 *  Can be used when changing these arrays to determine if the changes made sense.  
	 *  Please also run the unit test {@link RandomNameTest} then.  
	 *  And if necessary update the initial capacity of the {@link StringBuilder} which is used by
	 *  {@link #newNameBaseUnlimitedLength(String)}. */
	public static void main(String[] args) {
		out.println("Number of first names: " + firstnames.length);
		out.println("Number of last names:  " + lastnames.length);
		out.println();
		
		int firstnamesCharCount = 0;
		int lastnamesCharCount  = 0;
		
		for(String firstname : firstnames) firstnamesCharCount += firstname.length();
		for(String lastname  : lastnames)  lastnamesCharCount  += lastname.length();
		
		out.println("Average first name length: " + (float)firstnamesCharCount / firstnames.length);
		out.println("Average last name length:  " + (float)lastnamesCharCount  / lastnames.length);
		out.println();
		
		int minFirstLen = Integer.MAX_VALUE;
		int maxFirstLen = Integer.MIN_VALUE;
		
		int minLastLen  = Integer.MAX_VALUE;
		int maxLastLen  = Integer.MIN_VALUE;
		
		for(String firstname : firstnames) {
			minFirstLen = min(minFirstLen, firstname.length());
			maxFirstLen = max(maxFirstLen, firstname.length());
		}
		
		for(String lastname  : lastnames) {
			minLastLen  = min(minLastLen, lastname.length());
			maxLastLen  = max(maxLastLen, lastname.length());
		}
		
		out.println("Minimum first name length: " + minFirstLen);
		out.println("Maximum first name length: " + maxFirstLen);
		out.println();
		out.println("Minimum last name length:  " + minLastLen);
		out.println("Maximum last name length:  " + maxLastLen);
	}

	/** About 1538 first names which we use as template to generate random first name + last name
	 *  combinations.
	 *  
	 *  In 2022 ArneBab has attempted to make this equally balanced in terms of the count of female
	 *  and male names.  
	 *  An imbalance of about 2% may still exist towards male names because xor found some duplicate
	 *  names afterwards which were then removed to keep the list duplicate-free.  
	 *  Avoiding duplicates is a good idea because it allows the unit tests to check for duplicates
	 *  and fail if there are any. Considering the large size of the list manual checking would not
	 *  be feasible, so a unit test must exist.
	 *  
	 *  After changing this list please do what is described in the documentation of
	 *  {@link #main(String[])}.
	 *  
	 *  TODO: Code quality: Put the names into separate text files and load them as resources from
	 *  the JAR.  
	 *  For an example of how to do that see function {@link ISO639_3#loadFromTabFile()} at fred.
	 *  
	 *  TODO: Code quality: The next iteration of this code should split the template names into
	 *  sets, e.g. "femaleFirstnames", "maleFirstnames" (and possibly also "neutralFirstnames") to
	 *  always allow equal gender distribution of the generated names no matter the size of each of
	 *  the sets. */
    final static String[] firstnames = {
        "Aatsista", "Abbas", "Abbott", "Abd", "Abdel", "Abdol",
        "Abdul", "Abdus", "Abel", "Abolfadl", "Abraham", "Abu", "Abul",
        "Abulcasis", "Abū", "Achim", "Ada", "Adalbert", "Adam",
        "Addison", "Adele", "Adilson", "Adnan", "Adolf", "Adolfo",
        "Adolph", "Adolphe", "Adrian", "Adrien", "Agnodice", "Agostino",
        "Ahearn", "Ahmad", "Ahmed", "Aimé", "Air", "Akhtar", "Al",
        "Alain", "Alan", "Albert", "Alberte", "Alberto", "Albrecht",
        "Aldo", "Alec", "Alejandro", "Alessandra", "Alexander",
        "Alexandre", "Alexei", "Alexis", "Alexius", "Alfred", "Alhazen",
        "Ali", "Alice", "Alicia", "Alistair", "Allan", "Allen",
        "Allenna", "Allvar", "Alois", "Alonzo", "Alphonse", "Alsayed",
        "Altman", "Alvar", "Alvin", "Alwin", "Amalie", "Amasa",
        "Ambrose", "Ambrozic", "Amin", "Amir", "Anatol", "Anders",
        "Andreas", "Andrei", "Andrew", "André", "Andy", "Angélique",
        "Anil", "Animesh", "Anita", "Ann", "Anna", "Annie",
        "Anousheh", "Anselm", "Anthony", "Antoine", "Anton", "Antonella",
        "Antonia", "Antonio", "Antonius", "Aqa", "Arbour", "Arden",
        "Armand", "Armin", "Armstrong", "Arnaldo", "Arndt", "Arne",
        "Arnold", "Arnoult", "Arthur", "Arun", "Arvid", "Asad", "Asaph",
        "Aseem", "Ashok", "Ashoke", "Asper", "Athanase", "Athanasius",
        "Atul", "Auer", "August", "Auguste", "Augustin", "Augusto",
        "Augustus", "Aurel", "Avi", "Axel", "Axworthy", "Aziga", "Aziz",
        "Azizul", "Azod", "Ba", "Bacharuddin", "Bagshaw", "Bain",
        "Baldwin", "Balfour", "Baltovich", "Baltzar", "Bandura",
        "Bangxing", "Banū", "Barbara", "Barlaam", "Barlow",
        "Barrie", "Barringer", "Barry", "Bartholomew", "Bartolomeo",
        "Baruj", "Bascom", "Beatrice", "Beatty", "Becky", "Bee", "Beker",
        "Belaney", "Bell", "Belle", "Belsazar", "Ben", "Benedict",
        "Bengt", "Benjamin", "Benoît", "Berend", "Berger", "Bernard",
        "Bernardo", "Bernd", "Bernhard", "Bernt", "Berta", "Berthold",
        "Besette", "Beth", "Bethune", "Bhāskara", "Big", "Bigelow",
        "Bill", "Billy", "Bindy", "Bing", "Birbal", "Birjandi", "Bishop",
        "Biéler", "Bjarni", "Björn", "Black", "Blass", "Blaylock",
        "Blondin", "Blusson", "Bob", "Bombardier", "Bonnie", "Boris",
        "Bourassa", "Bourgault", "Boyd", "Boyle", "Braden", "Bradley",
        "Brant", "Brendan", "Brethren", "Brian", "Bridget", "Brigadier",
        "Broadbent", "Brockhouse", "Bronfman", "Brook", "Brossard",
        "Brother", "Brown", "Bruce", "Bruno", "Brunt", "Bryan", "Buck",
        "Bucke", "Bukhtishu", "Bull", "Burzoe", "Bégin", "Béla", "Bùi",
        "Bửu", "Cai", "Caleb", "Callaghan", "Callinicus", "Calvert",
        "Calvin", "Camille", "Campbell", "Campeau", "Captain",
        "Carbonneau", "Cardinal", "Carey", "Carl", "Carlo", "Carlos",
        "Carol", "Caroline", "Carolus", "Carroll", "Caryl", "Caspar",
        "Cassius", "Caten", "Cato", "Cecil", "Cecila", "Cecilia",
        "Celeste", "Cerny", "Cesare", "Chambers", "Chang", "Chante",
        "Chao", "Charles", "Charlotte", "Chauncey",
        "Chemistry", "Chen", "Chester", "Chiara", "Chief",
        "Chien", "Chien-Shiung", "Childs", "Chris", "Chrisholm",
        "Christian", "Christiane", "Christof", "Christoph",
        "Christophe", "Christopher", "Chu", "Clague", "Claire", "Clara",
        "Clarence", "Clark", "Claude", "Claudia", "Claus", "Cleopatra",
        "Clifford", "Coching", "Cohen", "Cojocaru", "Colin", "Colonel",
        "Conrad", "Constantine", "Constantinos", "Cooke", "Copps",
        "Corentin", "Corrado", "Cossette", "Craig", "Cummings", "Cumrun",
        "Cumshewa", "Cunning", "Currie", "Cynthia", "César", "Damian",
        "Dan", "Daniel", "Dankmar", "Danny", "Dave", "David", "Davidson",
        "Dean", "Death", "Debora", "Deborah", "Deepak", "Delfino",
        "Demetrius", "Dennis", "Derek", "Derry", "Desmarais", "Detlev",
        "Diamond", "Dian", "Dick", "Didymos", "Diederich",
        "Diederik", "Diedrich", "Dieter", "Dinawaree", "Ding",
        "Dionysios", "Dionysius", "Dixy", "Dmitri", "Dmytruk", "Dobbin",
        "Don", "Donald", "Donaldson", "Doris", "Dorothy",
        "Doug", "Dougal", "Douglas", "Dow", "Dr", "Dragoljub",
        "Dreimanis", "Dries", "Dwight", "Eastman", "Eaton", "Ebbers",
        "Ebenezer", "Eberhard", "Ed", "Edgar", "Edmond", "Edmund",
        "Edouard", "Edsger", "Eduard", "Edward", "Edwin", "Efstratios",
        "Eilhard", "Eleftherios", "Elena", "Eleuthère", "Eli", "Eliakim",
        "Elias", "Elijah", "Elisabeth",
        "Elizabeth", "Ellen", "Elliot", "Elmer", "Eloise",
        "Elsa", "Elsayed", "Elsie", "Elwin", "Eman", "Emanuel", "Emil",
        "Emile", "Emily", "Emmanuelle", "Emmy", "Engelbert", "Enne",
        "Enrico", "Enzo", "Ephraim", "Eric", "Erich", "Erik", "Erna",
        "Ernest", "Ernesto", "Ernst", "Erwin", "Esfarayeni", "Essam",
        "Esther", "Etienne", "Eugen", "Eugene", "Eugenio", "Eugène",
        "Eustachio", "Eustathius", "Eva", "Evangelista", "Evans",
        "Evliya", "Fabian", "Fabrice", "Faheem", "Fairclough", "Fanny",
        "Farabi", "Farghani", "Fariborz", "Farid", "Farkas", "Farouk",
        "Farsi", "Faten", "Fausto", "Fawzia", "Fazari", "Fazle",
        "Fazlur", "Federico", "Felice", "Felix", "Fenerty", "Ferdinand",
        "Ferdinando", "Ferdowsi", "Ferid", "Fernando", "Fessenden",
        "Feyz", "Fields", "Filippo", "Fisher", "Florence", "Florian",
        "Flossie", "Fonyo", "Fooke", "Foote", "Forrest", "Fortunio",
        "Fox", "Frances", "Francesco", "Francis", "Franciscus",
        "Francoise", "Frank", "Franklin", "Franks", "Frans", "Franz",
        "François", "Françoise", "Fraser", "Fred", "Frederick", "Frieder",
        "Friederich", "Friedrich", "Fritjof", "Fritz", "Frum", "Frye",
        "Frédéric", "Fuller", "Fullerian", "Félix", "Gabriel",
        "Gabrielse", "Gabrio", "Gaetano", "Gajendra", "Galbraith",
        "Galileo", "Gamal", "Ganapathi", "Gao", "Gardezi", "Gaspard",
        "Gaspare", "Gaston", "Geber", "Gene", "General", "Georg",
        "George", "Georges", "Georgi", "Georgios", "Gerald", "Gerard",
        "Gerd", "Gerhard", "Gerhart", "Germinal", "Gernot", "Gerry",
        "Gertrud", "Gertrude", "Gerty", "Gesner", "Ghiyāth", "Giacinto",
        "Giacopo", "Giambattista", "Gian", "Gianni", "Gianpiero",
        "Giauque", "Gilbert", "Gill", "Gilles", "Giorgio", "Giovanni",
        "Giuliano", "Giulio", "Giuseppe", "Gopalasamudram", "Gordon",
        "Goresky", "Gorgani", "Gosling", "Gottfried", "Gotthilf",
        "Gotthold", "Gottlob", "Grace", "Grady", "Graeme",
        "Granholm", "Grant", "Greg", "Gregor", "Gregorio", "Gregory",
        "Grete", "Grigori", "Grote", "Groulx", "Guenter", "Guglielmo",
        "Guido", "Guité", "Guo", "Guoray", "Gustaf", "Gustav",
        "Gustavus", "Guujaaw", "Guy", "Gyula", "Gösta", "Günter",
        "Günther", "Hakim", "Hal", "Hall", "Hallaj", "Haly", "Hamadani",
        "Hamed", "Hammad", "Haney", "Hannes", "Hanns", "Hans",
        "Hansen", "Har", "Harald", "Harawi", "Harish", "Harley",
        "Harlow", "Harold", "Haroon", "Haroutioun", "Harren",
        "Harriet", "Harriette", "Harrison", "Harry", "Hartmut", "Harvey",
        "Hasan", "Hasani", "Haskell", "Hassan", "Hawley", "Hawthorne",
        "He", "Heber", "Hechtman", "Hector", "Hedy", "Heide", "Heike",
        "Heiko", "Heinrich", "Heinz", "Helen", "Helga", "Helge",
        "Helmut", "Helmuth", "Hendrik", "Henning", "Henri", "Henrietta",
        "Henriette", "Henry", "Herbert", "Herman", "Hermann",
        "Herrick", "Hervé", "Herzberg", "Hessaby", "Hezarfen", "Hibat",
        "Hierocles", "Hieronymus", "Hildegard", "Hillier", "Hippolyte",
        "Hiram", "Hjalmar", "Ho", "Homayoun", "Homi", "Homolka",
        "Hongjia", "Hoodless", "Horace", "Horst", "Hotz", "Howard",
        "Howe", "Hsien", "Hubel", "Hubert", "Hugh", "Hugo", "Hulusi",
        "Humphrey", "Humphry", "Hunayn", "Hypatia", "Håkan", "Ian",
        "Ibn", "Ibrahim", "Ignacio", "Ignatieff", "Ignaz", "Igo",
        "Ikhwan", "Inge", "Ingo", "Innis", "Ioannes", "Ion", "Ioulianos",
        "Ira", "Irene", "Irit", "Irvine", "Irving", "Irène", "Isaac",
        "Isfahani", "Ishaq", "Ishfaq", "Ishrat", "Isidore", "Ivan",
        "Jabbo", "Jack", "Jacks", "Jacob", "Jacques", "Jafar",
        "Jagadish", "Jagdish", "Jagmohan", "Jakob", "James", "Jamshīd",
        "Jan", "Jane", "Janet", "Janice", "Janne", "Janus",
        "Jarrah", "Jay", "Jean", "Jeffrey", "Jegor", "Jennifer",
        "Jennings", "Jens", "Jeremy", "Jerome", "Jerry", "Jewgraf",
        "Jia", "Jiamo", "Jiang", "Jim", "Joan", "Joannes", "Joaquin",
        "Jochen", "Joe", "Johan", "Johann", "Johannes", "Johanson",
        "John", "Johns", "Johnson", "Jon", "Jonas", "Jonathan", "Jones",
        "Josef", "Joseph", "Joshua", "Josiah", "José", "Joy", "Joyce",
        "Joël", "Jules", "Julia", "Julie", "Julien", "Julius", "June",
        "Justin", "Justus", "János", "József", "Jöns", "Jørgen",
        "Jürgen", "Jābir", "Kailas", "Kajetan", "Kalidas", "Kamal",
        "Kamāl", "Karel", "Karin", "Karl", "Karol", "Kate", "Katharina",
        "Katherine", "Kathy", "Kazem", "Keen", "Kelvin", "Kenneth",
        "Kent", "Kerim", "Kesterton", "Kevin", "Keyes", "Khalid",
        "Khalil", "Kieran", "Killam", "Kim", "Kimura", "Kirstin",
        "Klattasine", "Klaus", "Klein", "Knut", "Kometas", "Konrad",
        "Kotcherlakota", "Koyah", "Kristian", "Kristin", "Krogh", "Kurd",
        "Kurt", "Kushyar", "Kyle", "Labib", "Labīd", "Lacombe",
        "Lagari", "Laliberté", "Lalji", "Lambton", "Lance", "Lanctôt",
        "Landon", "Landrum", "Langlois", "Laramie", "Larry", "Lars",
        "Latimer", "Laura", "Lauren", "Lawrence", "Layton", "Lazareanu",
        "Lazarus", "Lazzaro", "Le", "Lebrecht", "Lee", "Legere", "Leigh",
        "Leland", "Len", "Lennart", "Lenore", "Leo", "Leon", "Leonard",
        "Leonardo", "Leonhard", "Leonid", "Leontios", "Leopold",
        "Leopoldo", "Leslie", "Lester", "Lewis", "Li", "Libbie",
        "Lieselott", "Lieutenant", "Lillian", "Lisa",
        "Lise", "Liselotte", "Liu", "Lorenz", "Lorenzo",
        "Lorraine", "Lortie", "Loránd", "Lotfi", "Lothar", "Louis",
        "Lucien", "Lucius", "Luckett", "Ludolph", "Ludovic", "Ludvig",
        "Ludwig", "Luigi", "Luisa", "Luko", "Lutz", "Lybbert", "Lydia",
        "Lyman", "Lynn", "László", "Lépine", "Ma", "Macalister",
        "Macdonald", "Macedonio", "Mackay", "Macoun", "Macphail", "Mae",
        "Maged", "Magnus", "Mahbub", "Mahmoud", "Main", "Mainse",
        "Major", "Malcolm", "Mance", "Mandrake", "Manfred", "Manindra",
        "Manne", "Mansbridge", "Mansukh", "Mansur", "Manuel", "Maquinna",
        "Marc", "Marcel", "Marcela", "Marcellin", "Marcia", "Marcin",
        "Marco", "Marcus", "Marek", "Margaret", "Margarethe",
        "Marguerite", "Maria", "Marian", "Mariano",
        "Marie", "Marigny", "Marjorie", "Mark", "Markle", "Marks",
        "Marshall", "Marta", "Martin", "Martinus", "Mary",
        "Maryam", "Mathias", "Matt", "Matthew", "Matthias", "Matyáš",
        "Maurice", "Max", "Maxime", "Maximilian", "Maximus", "May",
        "Mayer", "Mead", "Meghnad", "Mehdi", "Mehmet", "Mehran",
        "Meinolf", "Melanie", "Melchisédech", "Melissa", "Menten",
        "Menyhért", "Merle", "Merrill", "Michael", "Michail", "Michel",
        "Michelangelo", "Middleton", "Mihajlo", "Mike", "Milgaard",
        "Mills", "Mir", "Mirko", "Mirza", "Mo", "Mohamed", "Mohammad",
        "Molson", "Monica", "Monika", "Monte", "Monty", "Morgan",
        "Morgentaler", "Morin", "Moritz", "Morrow", "Moshe", "Mostafa",
        "Mountjoy", "Moustafa", "Moustapha", "Mozaffar", "Muhammad",
        "Muhammed", "Muise", "Munir", "Munk", "Munro", "Murder",
        "Murray", "Mustafa", "Muḥyi", "Nachman", "Nader", "Naismith",
        "Najab", "Naldrett", "Nancy", "Napoleone", "Narendra", "Nasir",
        "Nat", "Nathan", "Nathanael", "Nathaniel", "Nazir", "Neil",
        "Nelson", "Neophytos", "Newman", "Nezami", "Nguyet", "Nicephorus",
        "Nicholas", "Nicola", "Nicolas", "Nicolaus", "Nicole",
        "Nicolò", "Niels", "Nikephoros", "Niketas", "Niklas", "Nikola",
        "Nikolai", "Nikolaos", "Nikolaus", "Nils", "Nima", "Nitya",
        "Niyaz", "Noam", "Noella", "Noga", "Norbert", "Noreen", "Norman",
        "Norwest", "Nur", "Nurbakhshi", "Ogden", "Olaus", "Olav",
        "Ole", "Olga", "Olinde", "Oliver", "Olson", "Omar", "Orest",
        "Ormsby", "Osborne", "Oscar", "Oskar", "Osler", "Othenio",
        "Othmar", "Ottaviano", "Otto", "Ottomar", "Ouyang", "Owen",
        "Padmanabhan", "Pafnuti", "Paikin", "Palmer", "Pan", "Pandurang",
        "Paolo", "Papineau", "Parker", "Pasquale", "Patcha",
        "Patriarch", "Patricia", "Patrick", "Pattison", "Paul", "Pedro",
        "Pegahmagabow", "Pehr", "Pei", "Peltier", "Penfield", "Per",
        "Percy", "Perri", "Pervez", "Pete", "Peter", "Philip", "Philipp",
        "Philippe", "Pickersgill", "Pickton", "Pierre", "Pieter",
        "Pietro", "Pinker", "Piri", "Pjotr", "Placidus", "Platon",
        "Polanyi", "Porritt", "Pouliot", "Prasanta", "Price", "Prince",
        "Prodromos", "Prof", "Prosper", "Qazi", "Qutb", "Qāḍī", "Rachel",
        "Rachid", "Rafi", "Raghunath", "Raimondo", "Rainer", "Rajeev",
        "Rakesh", "Ralf", "Ralph", "Ralston", "Ram", "Ramesh", "Ranajit",
        "Randi", "Randy", "Ranj", "Raoul", "Ray", "Raymond", "Razi",
        "Raziuddin", "Rear", "Rebecca", "Redpath", "Reeves", "Reichmann",
        "Reinhard", "Reinhold", "Ren", "Rene", "René", "Reyat",
        "Rhetorios", "Riaz", "Riazuddin", "Richard", "Rick", "Ricketts",
        "Riel", "Rita", "Rivard", "Robert", "Roberta", "Roberto",
        "Roberts", "Robertson", "Rocha", "Roddam", "Rodney", "Roger",
        "Rogers", "Roland", "Rolf", "Rollo", "Ron", "Ronald",
        "Rosalind", "Rosalinde", "Rosalyn", "Rose", "Ross", "Roth",
        "Rousseau", "Roy", "Royal", "Rudolf", "Rudolph", "Rumi", "Rune",
        "Rupert", "Ruth", "Ruttan", "Ryan", "Ryerson", "Rémy",
        "Rüdiger", "Sabine", "Sabourin", "Sabzevari", "Sackett",
        "Safer", "Saghani", "Saghir", "Sahl", "Saint", "Sake", "Salim",
        "Salimuzzaman", "Sally", "Salman", "Salomon", "Salvatore", "Sam",
        "Samarqandi", "Sameera", "Samir", "Samuel", "Sandra", "Sandy",
        "Sanford", "Sangster", "Sanjeev", "Saputo", "Sarah", "Sarakhsi",
        "Saul", "Saunders", "Schawlow", "Schindler", "Schlumberger",
        "Schnarre", "Scholes", "Scipione", "Scott", "Sean", "Sebastian",
        "See", "Selim", "Selye", "Sergei", "Sergey", "Serhij", "Sethus",
        "Seymour", "Shahid", "Shahrastani", "Shahrazuri", "Shams",
        "Shanti", "Shao", "Shapur", "Sharaf", "Sharp", "Shawn", "Shaykh",
        "Sheikh", "Sheila", "Shen", "Shi", "Shinya",
        "Shirazi", "Shirley", "Shoukai", "Shreeram", "Sicard", "Sidney",
        "Siegfried", "Siegmund", "Sigmund", "Silvanus", "Simard", "Simon",
        "Simpson", "Siméon", "Sir", "Siva", "Smith", "Sofia",
        "Sofja", "Sol", "Song", "Sophie", "Sophus",
        "Sotirichos", "Srinivasa", "St.", "Stacy", "Stairs", "Stam",
        "Stanley", "Stanton", "Starkman", "Steele", "Stefan", "Stefano",
        "Stefanos", "Stelck", "Stephanie", "Stephanos", "Stephen",
        "Stephenson", "Steve", "Steven", "Stewart", "Strangway",
        "Stronach", "Stuart", "Studholme", "Su", "Subramanyan",
        "Suhrawardi", "Sujoy", "Sultan", "Sultana", "Sun", "Sunatori",
        "Sundback", "Sunder", "Sunil", "Susanne", "Suzuki", "Svante",
        "Sven", "Sydney", "Syed", "Sylvestre", "Symeon", "Symons",
        "Sztybel", "Taché", "Taha", "Talgat", "Tamsin", "Tan", "Tanner",
        "Taqi", "Taryn", "Taube", "Taylor", "Tej", "Tekakwitha",
        "Terry", "Thatcher", "The", "Theo", "Theodigios", "Theodoghius",
        "Theodor", "Theodore", "Theodoros", "Theofilos", "This", "Thomas",
        "Thomson", "Thorvald", "Théodore", "Thériault", "Tiberius",
        "Till", "Tilley", "Tim", "Timotheos", "Timothy", "Tipu",
        "Tobias", "Todd", "Toffy", "Tom", "Tommaso", "Tong", "Tony",
        "Torsten", "Traugott", "Trinh", "Trota", "Trueman", "Truscott",
        "Tuan", "Tyrrell", "Uchida", "Ugo", "Ulisse", "Ulrich", "Ulugh",
        "Urbain", "Uriel", "Urry", "Usamah", "Utpal", "Uwe", "Vainu",
        "Valentin", "Vanier", "Vannoccio", "Vaughan", "Venkatraman",
        "Vernon", "Vickrey", "Vicky", "Victor", "Vidus", "Vijay",
        "Vikram", "Viktor", "Vilhelm", "Vincent", "Vincenzo", "Vinod",
        "Vinton", "Virginia", "Vito", "Vittorio", "Vladimir", "Volker",
        "Václav", "Waddah", "Walker", "Wallace", "Waloddi", "Walter",
        "Walther", "Wang", "Wangari", "Waqidi", "Ward", "Warder",
        "Warner", "Warren", "Wasylyk", "Watson", "Wei", "Wendell",
        "Weng", "Weniamin", "Werbowy", "Werner", "Wernher", "Weston",
        "Wickanninish", "Wiktor", "Wilbur", "Wilfried", "Wilhelm",
        "Willem", "William", "Williams", "Willson", "Willy", "Wilma",
        "Wilson", "Win", "Winegard", "Winifred", "Wladimir", "Wo",
        "Woldemar", "Wolfgang", "Wolfram", "Woodbine", "Woodrow",
        "Woodward", "Wu", "Władysław", "Xavier", "Xiangzhong", "Xiaobo",
        "Xie", "Xilingshi", "Xuong", "Yang", "Yao", "Yaqūb", "Ye",
        "Yehia", "Yehuda", "Yellapragada", "Yingjie", "York", "Yoshihiro",
        "Young", "Yu", "Yuanzhang", "Yumn", "Yusuf", "Zacharias",
        "Zachary", "Zaghloul", "Zarrin", "Zayn", "Zhang", "Zhao",
        "Zheng", "Zhou", "Zhu", "Zhuang", "Zimmer", "Zygmunt",
        "zahid", "Ányos", "Édouard", "Élie", "Émile",
        "Émilie", "Étienne", "Évariste"};

	/** About 3670 last names which we use as template to generate random first name + last name
	 *  combinations.
	 *  
	 *  After changing this list please do what is described in the documentation of
	 *  {@link #main(String[])}. */
    final static String[] lastnames = {
        "A.", "Abarth", "Abbas", "Abbās",
        "Abbe", "Abdollah", "Abdul", "Abdulaziz", "Abel",
        "Abenragel", "Abhay", "Abhyankar", "abi", "Abi",
        "Abidi", "Abolfadl", "Abol-fath", "Abol-hasan", "Abouleish",
        "Abraham", "Abu", "Achache", "Achard",
        "Acropolites", "activists", "actors", "Adam", "Adams",
        "Adelaide", "Adelson-Welski", "Adhémar", "Adler", "Admiral",
        "Adolf", "Adolph", "Aepinus", "Aeronautical", "Afek",
        "Afzal", "Agnes", "Agnethler", "Agrawal", "Agre",
        "Ahad", "Ahmad", "Ahmed", "Ahmet", "Aho",
        "Ahuja", "Aimee", "Airy",
        "Aitken", "a.k.a.", "Akhtar", "al", "Ala",
        "Alabbas", "Alan", "Alana", "Baghdaadi",
        "Baitar", "Balkhi", "Banna", "Battānī",
        "Albers", "Albert", "Bīrūnī", "Alboacen", "Būzjānī",
        "Alcock", "Darir", "Alderson", "Din", "Dīn",
        "Aldini", "Dowleh", "Aleksis", "Alexander", "Alexandre",
        "Alexandrinos", "Alexandrowitsch", "Alexejewitsch", "Fārisī", "Fazari",
        "Alfred", "Alfvén", "Gazzar", "Habib", "Hamīd",
        "Harrānī", "Ali", "Alī",
        "Istikmal", "Alivisatos", "Jawharī", "Jazzar",
        "Jurajani", "Kāshī", "Khatib", "Khāzin", "Khujandi",
        "Allah", "Allan", "Latif", "Allee",
        "Allègre", "Allen", "Allenby", "Allman", "Maghribī",
        "Majusi", "Muqaddasi", "Mutaminwas",
        "Nafis", "Alon", "Alonzo", "Aloysius", "Alpert",
        "Alphonse", "Qalasādī", "Qalqashandi", "Qasim", "Quff",
        "Qūhī", "Rahwi", "Alroy",
        "Rūmī", "Safa", "Samarqandī", "Shatir",
        "Alshaykh", "Alt",
        "Alter", "Thahabi", "Althaus", "Altmeyer",
        "Turabi", "Tūsī",
        "Alwall", "Yaman", "Zarqālī", "Alzinger",
        "Amaldi", "Amandus", "Amara", "Ambroise", "Ambronn",
        "Ambrose", "Ambrosius", "Amdahl", "Amed", "Amedeo",
        "Amici", "Amin", "Amoretti", "Ampère", "Amsler-Laffon",
        "an", "Anand", "Anant", "and", "Anderson",
        "Andræ", "André", "Andreae", "Andreas", "Andreessen",
        "Andrejewitsch", "Andrew", "Andrews", "Angas", "Ange",
        "Angelini", "Ångström", "Anh", "Annie", "an-Nu‘man",
        "Ansari", "Anschütz-Kaempfe", "Anthemius", "Anthony", "Antinori",
        "antiosteoporosis", "Antoine", "Anton", "Antonelli", "Antoni",
        "Antonio", "Antonucci", "Antoon", "Anwar", "AOE",
        "Appelbaum", "Appell", "Appelrath", "Apple", "application",
        "Apt", "Arago", "Arbib", "Archeologist", "Archer",
        "Archibald", "Archie", "Ardré", "Arfwedson",
        "Argand", "Argyros", "Arkani-Hamed", "Armstrong", "Arndt",
        "Arnett", "Arnold", "Aronhold", "Arora", "Arrhenius",
        "Arrighetti", "Arseneau", "Arsenjew", "Artemjew", "Arthur",
        "Artin", "artists", "Arturo",
        "Arzelà", "as", "Aschoff", "Ascoli", "Ashtekar",
        "Asker", "Aslam", "Aslihan", "Asperger",
        "Asplund", "astronomers", "Astrophysicist", "astrophysicists", "Atala",
        "Athanase", "Atiya", "Atkinson", "Atleo", "Attaliates",
        "Atwater", "Auenbrugger", "Auer", "Auerbach", "August",
        "Auguste", "Augustin", "Augustine", "Augustus", "Avery",
        "Avogadro", "Avolio", "Avram", "Axon", "Ayako",
        "Ayrton", "Azophi", "B.", "Baader", "Babai",
        "Babbage", "Babinet", "Bach", "Bache", "Bächler",
        "Bachman", "Bachmann", "Backlund", "Bäcklund", "Backus",
        "Badawi", "Baerwald", "Baghdadi", "Bailey", "Bain",
        "Bajjah", "Baker", "Balaram", "Baldwin", "Ball",
        "Balmer", "Baltzer", "Balzani", "Balzert", "Banda",
        "bands", "Banerjee", "Banting", "Bappu",
        "Baptiste", "Baptiste-Charles-Joseph", "Baqillani", "Baqir", "Bar",
        "Baran", "Bárány", "Barbara", "Barclay", "Baril",
        "Barker", "Barlow", "Baron", "Barratt-Boyes", "Barrett",
        "Bartels", "Bartholomäus", "Bartoli", "Basse", "Battista",
        "Battuta", "Bauer", "Baumann", "Baumgartner", "Bavink",
        "Bayer", "Bazaine", "Bear", "Bearpark", "Beaton",
        "Beauclair", "Beaverbrook", "Bechtolsheim", "Beck", "Becker",
        "Becquerel", "Beddington", "Beecher", "Beeck", "Beer",
        "Beetz", "Beg", "Behçet", "Behlendorf", "Bélanger",
        "Belgrado", "Bell", "Bellard", "Belli", "Bellocchi",
        "Beltrami", "Bement", "Bemer", "Ben", "Ben-Abraham",
        "Benacerraf", "Benedict", "Beneke", "Benischke",
        "Benjamin", "Bennett", "Benz", "Bergen", "Bergter",
        "Berkeley", "Berliner", "Berman", "Bernard", "Berners-Lee",
        "Bernhard", "Bernie", "Bernstein", "Berthelot", "Bertin",
        "Bertini", "Bertram", "Bertrand", "Berzelius", "Besha",
        "Bessel", "Bessières", "Bestelmeyer", "Beth", "Betrugi",
        "Bettelheim", "Betti", "Beurle", "Beurling", "Beutler",
        "Beverly", "Beyer", "Beynon", "Beyrich", "Bezold",
        "Bhabha", "Bhaktivedanta", "Bhatkar", "Bhatnagar", "Bialy",
        "Bianchi", "Bibi", "Biddell", "Bidwell", "Bieling",
        "Bienvenu", "Biere", "Bierens", "Bierstedt", "Bijl",
        "Bilal", "Billet", "Bimber", "bin", "Binet",
        "Biologist", "Biot", "Birchall", "Biringuccio", "Birkeland",
        "Birnbaum", "Bischofberger", "Bishop", "Bishop.", "Bittner",
        "Bjerhammar", "Bjerknes", "Black", "Blake", "Blakesley",
        "Blanc", "Blanchard", "Blandowski", "Blaschke", "Blaserna",
        "Blasius", "Blauert", "Bleher", "Blemmydes", "Bloch",
        "Bloede", "Blömer", "Blondel", "Blondlot", "Bloodworth",
        "Blow", "Blum", "Bob", "Bôcher", "Bode",
        "Bodenstein", "Boehm", "Boehmer", "Bogdandy", "Böhler",
        "Bohlin", "Bohlmann", "Böhm-Bawerk", "Bohn", "Bohnenberger",
        "Boie", "Bois-Reymond", "Bokhari", "Boll-Dornberger", "Bolter",
        "Boltzmann", "Bolyai", "Bolzano", "Bond", "Bondar",
        "Bondar.", "Bonnet", "Booch", "Book", "Boole",
        "Bopp", "Borchardt", "Borchert", "Borg", "Boris",
        "Borissowitsch", "Born", "Born-", "Börnstein", "Borzouyeh-i",
        "Bosak", "Bosch", "Bose", "Boslough", "Bossart",
        "Böszörményi", "Botto", "Bottomley", "Boulos", "Bouquet",
        "Bourgelat", "Bourgeois", "Bourgeoys", "Bourne", "Boussinesq",
        "Boussingault", "Bowditch", "Bowen", "Bowman", "Boyce",
        "Boyd", "Boyer", "Boyle", "Boys", "Brace",
        "Brachet", "Bradley", "Brandan", "Brandes", "Brandt",
        "Branislav", "Branly", "Brant", "Brashear", "Brassard",
        "Bratt", "Brauer", "Braun", "Bravais", "Bray",
        "Brébeuf", "Breguet", "Breislak", "Brenner", "Brent",
        "Brentano", "Bresenham", "Bretschneider", "Breuer", "Brewer",
        "Brewster", "Brian", "Brianchon", "Bricklin", "Briefs",
        "Brienza", "Briggs", "Brill", "Brillouin", "Brin",
        "Brioschi", "Briot", "Bristol", "Britz", "Broca",
        "Brocchi", "Brock", "Broder", "Brodhun", "Brooks",
        "brothers", "Brothers", "Brown", "Brownlee", "Broy",
        "Brubaker", "Bruce", "Brücke", "Bruckmann", "Brügge",
        "Brunel", "Brunhes", "Brunner-von", "Brunnstein", "Bruno",
        "Bruns", "Bry", "Bryant", "Bt", "Bubb",
        "Buber", "Bucherer", "Buchholz", "Büchi", "Buchmann",
        "Buckingham", "Budach", "Budiansky", "Buff", "Bunjakowski",
        "Bunker", "Buquoy", "Burali-Forti", "Burch", "Burdon-Sanderson",
        "Burg", "Burgard", "Burgay", "Burgdorfer", "Bürger",
        "Burja", "Burkewood", "Burkhardt", "Burmeister", "Burr",
        "Buschke", "Bussard", "Butement", "Butterworth", "Büttner-Janz",
        "Buys-Ballot", "Buytaert", "Buzjani", "by", "Byrne",
        "c.", "C.", "Cabane", "Cabanis", "Cade",
        "Cahn", "Cai", "Cailletet", "Cailliau", "Caine",
        "Cairncross", "Cajori", "Calder", "Calhoun", "Callaway",
        "Callister", "Calmette", "Calvisius", "Camaterus", "Cameron",
        "Camille", "Campbell", "Campbell-Howe", "can", "Canada",
        "Canadian", "Cancrin", "candidate", "Canettieri", "Canguilhem",
        "Cant", "Cantor", "Capilano", "Capra", "Caracristi",
        "Card", "Cardinal", "Carey", "Carini", "Carl",
        "Carlebach", "Carleson", "Carleton", "Carlo", "Carlson",
        "Carlsson", "Carmack", "Carnot", "Carpenter", "Carrick",
        "Carroll", "Carruthers", "Cartan", "Cartier", "Carucci",
        "Cäsar", "Caselli", "Casey", "Casorati", "Cassian",
        "Castellani", "Castillo-Chavez", "Catalan", "Cathy", "Catlin",
        "Catmull", "Caton", "Cauchy", "Cavallo", "Cayley",
        "Cecil",
        "Celebi", "Çelebi", "Célestin", "Celko", "Celsius",
        "century", "Century", "Cerami", "Cerf", "César",
        "Cesàro", "Cesi", "Chabanel", "Chain",
        "Chakmakjian", "Chakraborty", "Chakravorty", "Chalfie", "Chalmers",
        "Champneys", "Chand", "Chandra", "Chandrasekhar", "Chang",
        "Chapman", "Chappuis", "Charles", "Charpy", "Chasles",
        "Chastelain", "Châtelet", "Chattar", "Chaudhry", "Chauvenet",
        "Chazelles", "Che", "Chemist", "Chemist/Drug", "Chemistry",
        "Chen", "Cherry", "Chick", "chief", "Chilton",
        "Chin", "Ching-wu", "Chi-yun", "Chladni", "Chomsky",
        "Choniades", "Choniates", "Chortasmenos", "Choumnos", "Chrétien.",
        "Chris", "Christ", "Christian", "Christiansen", "Christie",
        "Christoffel", "Christoffer", "Christoph", "Christophe", "Christopher",
        "Chrobak", "Chroust", "Chrysokkokes", "Chrysoloras", "Chu",
        "Chua", "Church", "Chwolson", "Clah", "Clapeyron",
        "Clarence", "Claret", "Clark", "Clarke", "Claude",
        "Clausius", "Clebsch", "Clement", "Clément", "Clément-Désormes",
        "Clements", "Clerk", "Clifford", "Clifton", "Cluny",
        "Clyde", "Clynes", "CMM",
        "Cockayne", "Cockburn", "Cocke", "Coco", "Codazzi",
        "Codd", "Cohen", "Cohn", "Colding", "Cole",
        "Coles", "Colin", "Colladon", "Colmerauer", "Colonel",
        "Commodore", "Comnena", "Computer", "Comrie", "Conant",
        "Conrad", "Constant", "Constantine-Cyril", "Constantinople", "content.",
        "Contreras", "Converse", "Conway", "Cook", "Coons",
        "Cooper", "Copley", "Corbató", "Corell", "Cori",
        "Coriolis", "Cormier", "Cornelius", "Cornu", "Corwin",
        "Cosgrave", "Costaz", "Couch", "Coudres", "Couette",
        "Couffignal", "Cournot", "Courtial", "Courtillot", "Cousin",
        "Cousteau", "Coutelle", "Covert", "Cox", "Coy",
        "Coyne", "Craig", "Cramér", "Crandall",
        "Crandell", "Crane", "Cray", "Crear", "Creighton",
        "Crelle", "Cremona", "Creutzfeldt", "Crick", "Criegee",
        "Crivelli", "Crocco", "Croft", "Crofton", "Crookes",
        "Crosse", "Crossharbour", "Cruveilhier", "CSC/ASC", "Culliney",
        "Cumenge", "Cummins", "Cunard", "Cunningham", "Curie",
        "Curiel", "Currie", "Curry", "Curt", "Curtis",
        "Curtius", "Cushman", "Cutler", "Cuvier", "Cyprios",
        "Czapski", "Czuber", "d.", "D.", ".D.",
        "Dahl", "Dahm", "Dai", "Dalén", "Dalibard",
        "dalla", "Dallaire", "Dallas", "Dally", "Dalton",
        "Damietta", "Dan", "Dandelin", "Dandy", "Dani",
        "Daniel", "Danilowitsch", "Darboux", "DArch", "Darcy",
        "Daria", "Darley", "Darwin",
        "Dase", "dast", "Dathe", "Daudel", "Dausset",
        "Davenport", "David", "Davidoff", "Davidson", "Davies",
        "Davy", "Dawood", "Dawson", "DComm",
        "de", "De", "Dean", "Debevec", "Dedekind",
        "Deese", "del", "Delabarre", "Delamétherie", "Delbrück",
        "della", "Delpino", "DeMarco", "Deming", "Demonferrand",
        "Demopoulos", "Denenberg", "Denian", "Denis", "Denneau",
        "Denso", "DePauli-Schimanovich", "der", "des", "Desaguliers",
        "Descartes", "design.He", "Desjarlais", "Desmond", "Despretz",
        "Desvalls", "Detlef", "Detlev", "Deutsch", "Deville",
        "Dewdney", "Dewey", "Dhaliwal", "Dhaliwal.",
        "Dham", "di", "Diamond", "Dickstein", "Diderik",
        "Didymus", "Died", "Diels", "Dienger", "Diesterweg",
        "Dieterici", "Dijkstra", "Dilger", "Dillon", "Dingley",
        "Dini", "Dinur", "Dirac", "Dirichlet", "Dirksen",
        "Dirr", "Dittrich", "Divini", "Dizhou", "DLitt",
        "DMSc", "Dobler", "doctors", "Doernberg", "Dolderer",
        "Domagk", "Domenico", "Dominique", "Donald", "Donato",
        "Dongier", "Doniach", "Dopatka", "Doppler", "Doreen",
        "Dorigo", "Dorn", "Doty", "Dotzauer",
        "Doug", "Dove", "Draper", "Dresler", "Dressel",
        "Drobisch", "Droop", "Droysen", "Drude", "drug",
        "Druschel", "Dryander", "Dryden", "DSc", "DSC",
        "du", "Du",
        "Dudeney", "Dudoward", "Duesberg", "Duff", "Duhamel",
        "Duhem", "Dulong", "Dumas", "Duncan", "Dunn",
        "Duong", "Dupin", "Dupré", "Dupuis", "Duraid",
        "Durham", "Durrance", "Durrant", "Dury", "Duzheng",
        "Dvorak", "Dyck", "Dye", "e",
        "E.", "Earl", "early", "Earnshaw", "East",
        "Easton", "Eaton.", "Attar", "Eberhard", "Eberhardt",
        "Ebert", "Eckel", "Eckert", "Eckmiller", "Ed",
        "E.D.", "Ed-Din", "Edessinos", "Edgar",
        "Edison", "Edlén", "Edlund", "Edmond", "Edmund",
        "Édouard", "Eduard", "Edvard", "Edward", "Edwin",
        "Efesios", "Egertron", "Eglash", "Egyed", "Egypt.",
        "Egyptian", "Ehrenberg", "Ehrenfels", "Ehrenfest", "Ehrinn",
        "Ehrlich", "Eich", "Eichhorn", "Eichhorst", "Eigen",
        "Einstein", "Eisenlohr", "Eisenstein", "Eitel", "Ekeblad",
        "Ekman", "El", "el-Akkad", "el-Baghdadi", "El-Baz",
        "Eldon", "Electrical", "Elijah", "Elizabeth", "el-Latif",
        "Ellegård", "Ellen", "Ellis", "Ellison", "el-Mallakh",
        "El-Mashad", "Elmessiri", "Elmqvist", "El-Naggar", "Elsayed",
        "El-Sayed", "Elster", "Emanuel", "Emerson", "Emil",
        "Émile", "Emmett", "Emmons", "Encarnação", "Enders",
        "Enflo", "Engel", "Engelbart", "Engineer", "Engquist",
        "Ennemond", "Enneper", "Eötvös", "Eric", "Erickson",
        "Ericsson", "Erik", "Erman", "Ernest", "Ernst",
        "Ernster", "Erwin", "Erxleben", "Esaias", "Eschenmayer",
        "Escherich", "Eschwege", "Esmonde", "Essl", "Esson",
        "Eston", "et", "Ethel", "Etrich", "Ettingshausen",
        "Ettrich", "Eugen", "Eugène", "Eustachi", "Evelyn",
        "Everest", "Ewerbeck", "Ewing", "Exner", "experienced",
        "Eyck", "F.", "Faà", "Fabbroni", "Fabrizio",
        "Fabry", "Fadell", "Fadlan", "Fahim", "Fahlman",
        "Fakhri", "Falciani", "Falck", "Falk", "Famous",
        "Fanning", "Fano", "Farabi", "Faraday", "faraz",
        "Farber", "Fardella", "Farghani", "Faris", "Farkas",
        "Farrel", "Farrokh", "Fauque", "Féaux", "Fechner",
        "Feddersen", "Fehr", "Feige", "Feigenbaum", "Feigl",
        "Feilitzsch", "Feistel", "Feldman", "Felix", "Fellinger",
        "Felten", "Fensel", "Feodosjewitsch", "Ferchault", "Ferdinand",
        "Ferrara", "Ferrari", "Ferraris", "Ferrie", "Feuerbach",
        "Feuerlein", "Feuillée", "Feyerabend", "Ficinus", "Field",
        "Finch", "Finger", "Finke", "Finsterwalder", "Firmin",
        "Firnas", "Firsoff", "Fischer", "Fishman", "FitzGerald",
        "Five", "Fizeau", "Fjodorow", "Fjodorowitsch", "Flaherty",
        "Fleet", "Fleischl-Marxow", "Fleming", "Fletcher", "Fleurieu",
        "Floquet", "Florens", "Flory", "Flower", "Floyd",
        "focus", "Foerster", "Fogg", "Foing",
        "Foley", "Fontaine", "Forbes", "Forgy", "Forrester",
        "Förstemann", "Forsyth", "Forthomme", "Fortnow", "Fossel",
        "Fossey", "Foster", "Foucault", "Fourier", "Fowler",
        "Fox", "Frances", "Francesco", "Francis",
        "Franck", "Francoeur", "François", "Frank",
        "Franke", "Frankel", "Frankenheim", "Frankl", "Franklin",
        "Frankston", "Franz", "Frattini", "Fraunhofer", "Frazer",
        "Frédéric", "Frederick", "Frederik", "Fredholm", "Freeden",
        "Freeman", "Frege", "Freiherr", "Frenet", "Fresneau",
        "Fresnel", "Freud", "Frick", "Fricke",
        "Fridolin", "Friedlaender", "Friedman", "Friedrich", "Fries",
        "Friesenhausen", "Friis", "Frisch", "Frischauf", "Frobenius",
        "from", "Fronius", "Frosch", "Froude", "FRS",
        "Frullani", "Fu", "Fuchs", "Furbach",
        "Furrer", "Fuster", "Fuyu", "G.",
        "Gaafar", "Gabler", "Gaboury", "Gabriel", "Gächter",
        "Gadbled", "Gadefelt", "Gaden", "Gadgil", "Gaffer",
        "Gajdusek", "Galen", "Galiani", "Galilei", "Gallagher",
        "Gallant", "Gallese", "Galois", "Gambacorti-Passerini", "Gamma",
        "Gan", "Ganjavi", "Ganot", "Ganzhorn", "Ganzinger",
        "Gaolian", "Garbiński", "Garneau", "Garnett", "Garnier",
        "Gaspard", "Gaston", "Gates", "Gauss", "Gauß",
        "Gavreau", "Gay-Lussac", "Gaza", "GCB",
        "Gebelli", "Gegenbauer", "Gehrke", "Gehry",
        "Geinitz", "Geiser", "Geißler", "Geitel", "Gemelli",
        "General", "geographer", "Geographical", "Geometres", "geomorphologist",
        "Georg", "George", "George-Étienne", "Georges", "Gerald",
        "Gerard", "Gerber", "Gergonne", "Gerhard", "Gerling",
        "Germain", "Gernez", "Gerono", "Gerry", "Gersten",
        "Gerstner", "Gervais", "Gerzon", "Gesner", "Gettys",
        "Ghaboos", "Ghazali", "Ghica", "Ghiorso", "Ghoneim",
        "Ghulam", "Gibbs", "Gideon", "Gieseke", "Gifford",
        "Gilbert", "Gilbreth", "Gilman", "Giloi", "Gintl",
        "Girouard", "Gitt", "Giudice", "Givens", "Glaisher",
        "Glan", "Glantz", "Glaser", "Gleick", "Gleixner",
        "Glock", "Gluschkow", "Glykas", "Gmachl",
        "Gobind", "Goble", "Goddard", "Gödel", "Gohar",
        "Goher", "Göhner", "Golay", "Gold", "Goldberg",
        "Goldstein", "Golizyn", "Golz", "Gompertz", "Gomperz",
        "Goodenough", "Goodfield", "Goodman", "Goodwin", "Göpel",
        "Gordan", "Gordon", "Gorgani", "Gorini",
        "Gorrie", "Gosling", "Gosnell", "Gösta", "Gottfried",
        "Gottlieb", "Gould", "Goupil", "Goursat", "Gouy",
        "Grace", "Grady", "Graefe", "Graetz", "Gräffe",
        "Graffi", "Graham", "Gram", "Graßmann", "Graves",
        "Grawe", "Grayson", "Graziano", "Green", "Greenaugh",
        "Greenberg", "Greene", "Greenhill", "Gregoras", "Gretschel",
        "Griesbach", "Griess", "Grigorjewitsch", "Grilleau", "Grmek",
        "Gröbner", "Grodzinsky", "Gross", "Grossberg", "Grosseteste",
        "Grotthuß", "Grunert", "Grünwald", "Gruson", "Gudermann",
        "Guérin", "Gugler", "Guha", "Guillaume", "Guillemin",
        "Guinier", "Guldberg", "Gullstrand", "Gumlich", "Gunanoot",
        "Günther", "Guo", "Guozhi", "Gustaf",
        "Gustafson", "Gustav", "Gustave", "Guthrie", "Guy",
        "Guye", "Gwynne-Vaughan", "H.", "Haan",
        "Haas", "Haast", "Habachi", "Haber", "Habert",
        "Habibie", "Hachette", "Hacquet", "Hadamard", "Hadermur",
        "Hadfield", "Hagenbach-Bischoff", "Hahn", "Hairston", "Hajjāj",
        "Hakim", "Hales", "Halid", "Hall", "Hallaschka",
        "Hallowes", "Hallwachs", "Halphen", "Halsted", "Ham",
        "Hamadani", "Hamaker", "Hamdani", "Hameed", "Hamel",
        "Hamid", "Hamilton", "Hammer-Purgstall", "Hammond", "Hanafi",
        "Hang", "Hanganu", "Hanifa", "Ḥanīfa", "Hankel",
        "Hann", "Hannibal", "Hans", "Hansen", "Haq",
        "Haque", "Harawi", "Harcourt", "Harding", "Harkness",
        "Harnack", "Harold", "Harper", "Harris", "Harrison",
        "Harry", "Hart", "Hartland", "Hartmann", "Hartner",
        "Hartwell", "Harvey", "has", "Hasan", "Hasenöhrl",
        "Haskins", "Hass", "Hassan", "Hassanein", "Hasselmo",
        "Hassenfratz", "Håstad", "Hastings", "Hauber", "Hauck",
        "Hayan", "Hayek", "Hayes", "Haytham", "Hayyān",
        "He", "Heather", "Heaviside", "Heawood", "Hector",
        "Heeren", "Heffter", "Hegazi", "Heiberg", "Heider",
        "Heikal", "Heine", "Heinrich", "Heintz", "Heis",
        "Heisenberg", "Heliopolis", "Hell", "Heller", "Hellmann",
        "Hellwig", "Helm", "Helmert", "help", "Hemdan",
        "Heng", "Henize", "Henle", "Henneberg", "Hennert",
        "Henri", "Henrici", "Henrik", "Henry", "Hensel",
        "Hensley", "Herapath", "Herat", "Herbert", "Herbst",
        "Herforth", "Herglotz", "Hermann", "Hermes", "Hermite",
        "Herrmann", "Hershey", "Hertz", "Hess", "Hessaby",
        "Hesse", "Hessel", "Hessenberg", "Hettner", "Heun",
        "Heuser", "Heywood", "Hierholzer", "Higgins", "Hilbert",
        "Hilferding", "Hill", "Hillaire", "Hillenkamp", "Hillman",
        "Himstedt", "Hinrichs", "Hinrichsen", "Hinton", "Hippocrates",
        "Hirn", "Hirsch", "Hirst", "his", "historian",
        "historians", "Historiography", "Hittorf", "Hjelmslev", "Hobson",
        "Hockham", "Hoeflin", "Hoffmann", "Hofmann", "Hofmeister",
        "Hoge", "Hội", "Hoissen", "Holborn", "Hölder",
        "Holland", "Hollander", "Hollywood", "Holm", "Holmboe",
        "Holmes", "Holtz", "Homer", "Hoodbhoy", "Hoover",
        "Hopkins", "Hopkinson", "Hopper", "Hora", "Hörmander",
        "Hornaday", "Horne", "Horner", "Horsley", "Hörz",
        "Hosler", "Hough", "Hovanes", "Howard", "Hsu",
        "Hu", "Huang", "Hubal", "Hubert", "Hübner",
        "Hud", "Hudak", "Huggins", "Hugh", "Hugoniot",
        "Hull", "Hülße", "Hultz", "Humbert", "Humboldt",
        "Hunter", "Hurley", "Hurrelmann", "Hurst", "Hurwitz",
        "Husayn", "Husband", "Hussain", "Hussein", "Husserl",
        "Huth", "Hyde", "Hyrtl", "i", "I",
        "ibn", "Ibn", "Ibrahim", "Ibrāhīm", "Idrisi",
        "Ignatz", "Iles", "Ilyas", "Imad",
        "Imam", "Imhof", "Immanuel", "in", "In",
        "Inderjit", "information", "Information", "Inoué", "Interio",
        "introducing", "invented", "Iqbal", "Irene", "Irina",
        "Irwin", "Isa", "Isaac", "Isaacs", "Isadore",
        "Isenkrahe", "Ishaq", "Ishāq", "islam", "Islam",
        "Islamic", "Isma‘il", "Ismail", "it.", "Ivanovitch",
        "Ivar", "Ivory", "Iwanowitsch", "Iyer", "Izaak",
        "Izzy", "J.", ".J.", "Jaber", "Jābir",
        "Jack", "Jacob", "Jacobi", "Jacobs", "Jacobson",
        "Jacques", "Jacquin", "Jäger", "Jahiz",
        "Jain", "Jakob", "Jakosky", "Jakowlewitsch", "Jalaleddin",
        "James", "Jamin", "Jamshīd", "Jandera", "Janet",
        "Jason", "Jaumann", "Javan", "Jawhari", "Jay",
        "Jayant", "Jayyani", "Jazari", "Jazla", "Jean",
        "Jeanne", "Jedlik", "Jeffrey", "Jeffreys", "Jegorowitsch",
        "Jemison", "Jenkins", "Jenness", "Jennifer", "Jensen",
        "Jerrard", "Jessica", "Jhoti", "Ji", "Jiadong",
        "Jiazhen", "Jiazheng", "Jim", "Jinliang", "Jiuzhang",
        "Joel", "Jogues", "Johal", "Johan", "Johann",
        "Johannes", "Johansson", "John", "Johnson", "Johnston",
        "Johnstone", "Joliot-Curie", "Jolly", "Jonas", "Jones",
        "Jonquières", "Jordan", "Jöreskog", "José", "Josef",
        "Joseph", "Joseph-Armand", "Joule", "Jouzel", "Jr.",
        "Jubb", "Julianus", "Julien", "Julius", "July",
        "Jun", "Jung", "Jürgen", "Jusuf", "K",
        "K.", "Kadich", "Kaempfer", "Kagan", "Kakodkar",
        "Kalam", "Kalko", "Kallenberg", "Kallmann", "Kalm",
        "Kamal", "Kamel", "Kamerlingh", "Kāmil", "Kämtz",
        "Kane", "Kanfer", "Kanner", "Kantakouzenos", "Kao",
        "Kaplan", "Kaprekar", "Karaji", "karak", "Karas",
        "Kardar", "Karl", "Karla", "Karmarkar", "Károly",
        "Karoui", "Karsten", "Kashani", "Kasner", "Kaspar",
        "Kassem", "Kastner", "Kateri", "Kaufmann", "Kaul",
        "Kavka", "Kawaoka", "Kayser", "KBE",
        "Kearton", "Keck",
        "Keeler", "Keeling", "Keil", "Keith", "Kekulé",
        "Kellner", "Kelly", "Kelsen", "Kelvin", "Kempe",
        "Kempelen", "Ken", "Kenneth", "Kenny", "Kent",
        "Kerékjártó", "Kerimov", "Kermani", "Kerr", "Kervran",
        "Keshia", "Kessler", "Keyser", "Khaldun", "Khalil",
        "Khalili", "Khan", "Khankhoje", "Khan-Mayberry", "Khaseb",
        "Khatima", "Khatsahlano", "Khayyám", "Khazini", "Khorana",
        "Khorasan", "Khordadbeh", "Khwarizmi", "Khwārizmī", "Kidson",
        "Kiepert", "Kilbourne", "Killian", "Killing", "Kils",
        "Kim", "Kincaid", "Kindi", "King", "Kingdon",
        "Kinkelin", "Kinnamos", "Kinnersley", "Kircher", "Kirchhoff",
        "Kirkman", "Kirschstein", "Kitab", "Klawdijewitsch", "Klebs",
        "Klein", "Klemenčič", "Kloor", "Klump", "Kneser",
        "Knoblauch", "Knoch", "Known", "Knudsen", "Köberle",
        "Kobilka", "Koch", "Koenig", "Koenigsberger", "Koepsel",
        "Köhler", "Kohlrausch", "Kohn", "Kohnen", "Kolberg",
        "Kölreuter", "Kompfner", "König", "Kopans", "Köppen",
        "Korbuly", "Korkin", "Körner", "Korselt", "Korteweg",
        "Köstlin", "Kovalevskaya", "Kowalewskaja", "Kraft", "Kramer",
        "Krauss", "Krauß", "Krauter", "Krazer", "Krebs",
        "Kress", "Kricfalusi", "Kristelli", "Krochmal", "Kronecker",
        "Kronke", "Krylow", "Kubach", "Küch",
        "Kuczynski", "Kugler", "Kuhl", "Kuhn", "Külp",
        "Kumar", "Kummer", "Kundt", "Kuo", "Kurlbaum",
        "Kussmaul", "Kuwabara", "Kwang", "Kwolek", "Kyan",
        "L.", "la", "Labban", "Lacroix", "Lacy",
        "Ladislav", "Ladwig", "Lafontaine", "Lafresnaye", "Laguerre",
        "Laidlaw", "Laisant", "Laitman", "Laiyan", "Lal",
        "Lalande", "Lallemand", "Lallemant", "Lamarck", "Lamarr",
        "Lamb", "Lamé", "Lamm", "Lamont", "Lampe",
        "Lamy", "Land", "Landauer", "Landell", "Landgraf",
        "Landsberg", "Landsteiner", "Lane", "Lang", "Langbein",
        "Lange", "Langenmantel", "Langguth", "Langley", "Langmuir",
        "Langsdorf", "Langsdorff", "Lanpo", "Lans", "Lanzavecchia",
        "Laplace", "Lardner", "Larmor", "Larry", "Lassell",
        "Laßwitz", "Latimer", "Latin", "Laubier", "Launhardt",
        "Laurent", "Lautmann", "Laval", "Lawrence", "Lazarsfeld",
        "Le", "leader", "Leamington", "Lebanon", "Lebedew",
        "Lebesgue", "Lecher", "Ledley", "Lee", "Lefroy",
        "Legendre", "Leger", "Léger", "Lehmann", "Lehmus",
        "Leibniz", "Leiste", "Lejeune", "Lemnios", "Lemoine",
        "Lenard", "Lennard-Jones", "Lennox", "Lenoir", "Lenormand",
        "Lenz", "Leon", "Léon", "Leonard", "Léonard",
        "Lerch", "Leroux", "Lersch", "Leslie", "Lévy",
        "Lewis", "Lhuilier", "Li", "Liao", "Libri",
        "Liceti", "Lichtenberg", "Lie", "Liebenthal", "Liebig",
        "Liebson", "Liedtke", "Liénard", "Lightfoot", "Lilienthal",
        "Lilly", "Linda", "Lindelöf", "Lindemann", "Lindo",
        "Lindqvist", "Lindsay", "Linnaeus", "Lino", "Lionel",
        "Liouville", "Lioy", "Lippmann", "Lipschitz", "Lis",
        "Lisiecki", "Lisker", "Lisle", "Lissajous",
        "Listing", "Liu", "Ljapunow",
        "Lloyd", "Lo", "Lobatschewski", "Locard", "Lochs",
        "Lodge", "Loewenherz", "Loewi", "Loewy", "Löffelholz",
        "Logan", "Lohman", "Lommel", "Loomis", "Lord",
        "Lorentz", "Lorenz", "Loschmidt", "Louie", "Louis",
        "Louise", "Louis-Hippolyte", "Louis-Joseph", "Love", "Lovelace",
        "Lovering", "Löwdin", "Löwenstern-Kunckel", "Lübsen", "Lucas",
        "Lucien", "Ludvig", "Ludwig", "Luebbers", "Luhmann",
        "Luís", "Lumer", "Lummer", "Lundmark", "Lüroth",
        "Lux", "Lwowitsch", "Lykites", "Lykken", "Lyle",
        "Lymburner", "Lyon", "M.", "MacCullagh", "MacDiarmid",
        "Macdonald", "Macfarlane", "Mach", "Machura", "Mack",
        "MacKay", "Mackenzie", "Maclaurin", "MacLean", "MacMahon",
        "Macquorn", "MacWhinney", "Madan", "Madic", "Madison",
        "Maestlin", "Magister", "Magnus", "Mahalanobis", "Mahani",
        "Mahkan", "Mahmoud", "Mahmud", "Mahomet", "Mainardi",
        "Mairan", "Majid", "Major", "Majriti", "Malaise",
        "Malherbe", "Mallard", "Malmstén", "Malus", "Mangoldt",
        "Mansuète", "Mansur", "Manuel", "Mao", "Maqrizi",
        "Marburger", "Marc", "Marcellino", "March", "Marcus",
        "Margaret", "Marguerite", "Margulis", "Maria", "Marie",
        "Markow", "Marmur", "Marrakushi", "Marsh", "Marshall",
        "Marth", "Martin", "Martin-Löf", "Marum",
        "Marwazi", "Marx", "Mary", "Maryanoff", "Mascart",
        "Maschke", "Mash", "Mashelkar", "Masihi",
        "Masquelier", "Masʾūd", "Masudi", "Masuya", "Matar",
        "Mataré", "Mathematical", "Mathematician", "Mathew", "Mathias",
        "Mathieu", "Mathur", "Matteucci", "Matthaeus", "Matthew",
        "Matthews", "Matthiessen", "Maud", "Maude", "Mauderli",
        "Maududi", "Maupertuis", "Maurice", "Maury", "Mawardi",
        "Max", "Maximilian", "Maximowitsch", "Maxwell", "Mayer",
        "Mayr",  "McCafferty",
        "McCarthy", "McCarty", "McClintock", "McCollough", "McCormick",
        "McCrae", "McCrae.", "McFarlane", "McGaugh", "McIndoe",
        "McKubre", "McLaughlin", "McLean", "McNab", "McNaughton",
        "Mebel", "Medicinal", "Mehdi", "Mehler", "Mehmke",
        "Meidinger", "Meier", "Meighen", "Meinong",
        "Meissel", "Meitner", "Mejdell", "Melde", "Melitene",
        "Mellin", "Melloni", "Melveger", "Mendelssohn", "Mendenhall",
        "Mengchao", "Menger", "Ménière", "Merck", "Merkel",
        "Merlin", "Merritt", "Mertens", "Mervyn", "Meslin",
        "Mesmer", "Messerschmidt", "Metallurgical", "Metochites", "Metzner",
        "Meucci", "Mewburn", "Meyer", "Michael", "Michailowitsch",
        "Michel", "Michelson", "Micura", "Mikros", "Miletus",
        "Millard", "Miller", "Milne-Edwards", "Milner", "Minding",
        "Mindlin", "Minkowski", "Mir", "Mirzakhani", "Mises",
        "Miskawayh", "Mitchel", "Mitchell", "Mitja", "Mittag-Leffler",
        "Mitterhofer", "Möbius", "Mohammad",
        "Mohammed", "Mohmand", "Mohsen", "Moira", "Molecular",
        "Molien", "Moll", "Moller", "Mollet", "Mollier",
        "Mollweide", "Monachos", "Monaco", "monarchs", "Monge",
        "Monika", "Monique", "Monod", "Montgomery", "Montmor",
        "Moore", "Moosbrugger", "Morera", "Morgagni", "Morgan",
        "Morgenstern", "Moriarty", "Morin", "Moritz", "Morley",
        "Moro", "Morrison", "Mortimer", "Moscati", "Moschopulus",
        "Moser", "Mosharafa", "Mosher", "Mossotti", "most",
        "Motter", "Motwani", "Moura", "Mousharafa", "Moussa",
        "Moustafa", "Mouton", "Mozer", "MSM",
        "Muhammad", "Muir", "Müller", "Mullins", "Munke",
        "Munqidh", "Munro", "Murad", "Murphy", "Murray",
        "Musa", "Mūsā", "Musabayev", "Musgrave", "Musharafa",
        "musicians", "Musivand", "Muslim", "Muszaphar",
        "Muwaffak", "Myron", "Mystic-philosopher", "N.",
        "Nabatiye", "Nagel", "Nahanee", "Nahar", "Nahavandi",
        "Nahum", "Nappi", "Naqi", "Naqvi", "Narasimha",
        "Narayana", "Nardelli", "Narlikar", "Nasawi", "Nason",
        "Nasr", "Nasser", "Nat", "Nath", "Nathan",
        "Nathusius", "Natterer", "Nau", "Naumann", "Navier",
        "Nayfeh", "Nayrizi", "nd", "Near", "Nebel",
        "Negrelli", "Neil", "Nell", "Nelson", "Neophytos",
        "Netravali", "Netting", "Netto", "Neugebauer", "Neuman",
        "Neumann", "Neumayer", "Neuner", "Neurath", "new",
        "Newcomb", "Newhook", "Newton", "Nguyen-Huu", "Nichola",
        "Nicholas", "Nichols", "Nicol", "Nicolai", "Nicolas",
        "Nicollet", "Niger", "Nikolajewitsch", "Nishaburi", "no",
        "Noack", "Noailles", "Nobel", "Nobili", "Noël",
        "Noether", "Nolfi", "Noll", "Nordenskiöld", "Nordmark",
        "Norman", "Nörrenberg", "Norris", "North", "Northrop",
        "North-West", "Norton", "Noulet", "Nowak", "Nuclear",
        "Nurun", "Nuu-chah-nulth", "Nyberg", "Nye", "O.",
        "Obermaier",
        "Odlanicki", "Oettingen", "Oettinger", "of",
        "Ogilvie", "Ohm", "Oliver",
        "Olivi", "Olov", "Olovolos", "Olshansky", "Olszewski",
        "Oltmanns", "on", "ONB",
        "one", "Onnes", "OOnt", "Oppitz", "OQ",
        "or", "Orchard", "Oriental", "Orshansky", "Ørsted",
        "Ortmann", "Osann", "Osgood", "Ossian", "Ostell",
        "Osterloh", "Ostorlabi", "Ostrach", "Ostrogradski", "Ostry",
        "Otte", "Otto", "Ottokar", "Ottolini", "Öz",
        "P.", "Paalzow", "Pachymeres", "Packard",
        "Padé", "Page", "Painlevé", "painters", "pakistan",
        "Pal", "Palágyi", "Palay", "Palermo", "Palestinian-American",
        "Palmgren", "Palmieri", "Pandey", "Panitz", "Pantone",
        "Paoletti", "Papperitz", "Parascandola", "Pariser", "Parish",
        "Parke", "Parker", "Parrot", "Parseval", "particle",
        "Particle", "Pascal", "Pasch", "Pasteur", "Patricius",
        "Patrikios", "Pätsch", "Patterson", "Paul", "Paul-Émile",
        "Pauli", "Paull", "Pausch", "Payette", "PC",
        "Peacock", "Peakall", "Peano", "Pearkes", "Pearson",
        "Peckolt", "Péclet", "Pedersen", "Pediasimos", "Peijian",
        "Peirce", "Peltier", "Penninger", "Pentland", "Penyngton",
        "Pepagomenos", "Perkins", "Perlis", "Perlovsky", "Pérot",
        "Perrin", "Persian", "personalities", "Perutz", "Pete",
        "Peter", "Peters", "Petersen", "Petit", "Petr",
        "Petrina", "Petrini", "Petter", "Pettit", "Petzval",
        "Peyton", "Pezzo", "Pfaff", "Pfaundler", "Pfefferle",
        "Pfeiffer", "Pferd", "PhD", "Philip", "Philipp",
        "Philippe", "Phillip", "Phillips", "Philoponus", "Philosopher",
        "Phong", "Photius", "Phragmén", "physician", "physicist",
        "Physicist", "Picard", "Pichon", "Pichot", "Pickel",
        "Pickering", "Pictet", "Piddington", "Pierce", "Pierpont",
        "Pierre", "Piers", "Pike", "Pinart",
        "Pincherle", "Pineo", "Piola", "pioneers", "Pirquet",
        "Pisa", "Pisani", "Pisidis", "Pispers",
        /* Yes, this is an easter egg. About one in 6 Million names
         * will be Volker Pispers :) */
        "Pitman", "Pixii", "Plana", "Planck", "Planté",
        "Planudes", "Plateau", "Platen", "Playfair", "Pleijel",
        "Plendl", "Plötner", "Plücker", "Pochhammer", "Pockels",
        "Poczobutt", "Podolynskyj", "Poduska", "Poggendorff", "Pohl",
        "Poincaré", "Poinsot", "Point", "Poiseuille", "Poisson",
        "Poivre", "Pokrajac", "Pol", "Polhem", "Poli",
        "Polyakov", "Polycarp", "Pona", "Poncelet", "Pope",
        "Popow", "Poppe", "Popper", "Porezki", "Porges",
        "Porsche", "Porta", "Pösch", "Poste", "Postel",
        "Potrykus", "Potts", "Pouillet", "Pourmand", "Power",
        "Powers", "Poynting", "Prabhupada", "Prasse", "Pratt",
        "Pregl", "Prem", "Prescott", "Preston", "Prévost",
        "Pribram", "Price", "Priestley", "primary", "Pringsheim",
        "Prinz", "Priscu", "Probstein", "Prodi", "Prodromos",
        "Professor", "Proteus", "Prout", "Prym", "Psellus",
        "Pu", "Puch", "Puiseux", "Pullman", "Puluj",
        "Pupin", "Purity", "Qadeer", "Qavameddin", "Qazvini",
        "Quélet", "Quevedo", "Quincke",
        "R.", "Raabe", "Rabban", "Rabdas",
        "Rabl", "Radandt", "radio", "Radon", "Raghava",
        "Rahman", "Ralston", "Ramachandra", "Ramachandran",
        "Ramakrishnan", "Raman", "Ramanujan", "Rampone", "Ramsayer",
        "Ramsey", "Ramsoomair", "Randall", "Randles", "Randolph",
        "Rangadhama", "Rank", "Rankine", "Ranvier", "Rao",
        "Raoult", "Raper", "Rapley", "Rapoport", "Raps",
        "Rashid", "Raskin", "Rattenbury", "Rayhān", "Rayleigh",
        "Raymond", "Razdan", "Réaumur", "Rebellion", "Rebellion.",
        "Reber", "Rechtschaffen", "Recknagel", "Red", "Reda",
        "Reddy", "Reece", "Rees", "Reginald", "Regnault",
        "Reich", "Reick", "Reiff", "Reinhold", "Reis",
        "Reiss", "Reitlinger", "religions", "Remez", "Ren",
        "René", "Rescinded", "Reski", "Resnick", "Ressel",
        "Reuss", "Reye", "Reynolds", "Rhodes", "Rhyne",
        "Ribbentrop", "Ricci-Curbastro", "Richard", "Richelot",
        "Richmond", "Richter", "Richthofen", "Rick", "Rickard",
        "Riddell", "Ridker", "Ridwan", "Riecke", "Riedl",
        "Riefler", "Riel.", "Riemann", "Rieß", "Rife",
        "Righi", "Ringel", "Rinner", "Rittenhouse",
        "Ritter", "Ritz", "Riva-Rocci", "Rive", "River",
        "Robb", "Robbins", "Robert", "Roberts",
        "Robinet", "Robinson", "Rocco", "Roch", "Rock",
        "Roden", "Rodrigues", "Rodriguez-Iturbe", "Rodwell", "Roger",
        "Rogers", "Rogowski", "Rohn", "Rohr", "Romagnosi",
        "Romano", "Roméo", "Ron", "Röntgen", "Rood",
        "Rosa", "Rosanes", "Rösch", "Rosemary", "Rosen",
        "Rosenhain", "Rosin", "Rosnay", "Ross", "Rossby",
        "Rostam", "Roth", "Rouché", "Rous", "Rouse",
        "Routh", "Roux", "Rowan", "Rowland", "Roy",
        "Royal", "Rubens", "Rudbeckius", "Rudio", "Rudolf",
        "Rudolph", "Ruffin", "Ruffini", "Rugg", "Ruggiero",
        "Rumpler", "Runge", "Ruoff", "Rusk", "Russell",
        "Rustah", "Rutherford", "Ruzicka", "Rydberg", "s",
        "S.", "Saalschütz", "Sabieh", "Sabine", "Sachs",
        "Sachsen-Weimar-Eisenach", "Sadashiv", "Sadegh-Zadeh", "Sadi", "Sadiq",
        "Saduq", "Saeed", "Safdie", "Saghani", "Saha",
        "Sahba", "Sahl", "Sahni", "Said",
        "Saint-Venant", "Sajad", "Salam", "Salcher", "Salinger",
        "Salisbury", "Salman", "Salmon", "Salomo", "Salomon",
        "Saltzman", "Salviati", "Sam", "Samantha", "Samawal",
        "Samudrala", "Samuel", "Samuelian", "Sandberger", "Sanders",
        "Sandford", "Sangro", "Sanli", "Sarabhai", "Sarasin",
        "Sarrabat", "Sarrus", "Saud", "Savart", "Saverio",
        "Saxton", "Sayyid", "S.B.", "ScD", "ScDMil",
        "Schaeffer", "Schäfer-Korting", "Schafhäutl", "Scharrer", "Scheel",
        "Scheele", "Scheffers", "Scheffler", "Scheidel", "Schering",
        "Scherk", "Schilling", "Schläfli", "Schlegel", "Schlesinger",
        "Schlick", "Schlögl", "Schlömilch", "Schmidt", "Schmitt",
        "Schneider", "scholar", "Scholar", "Schönflies", "Schore",
        "Schott", "Schottky", "Schoute", "Schrader", "Schröder",
        "Schrödinger", "Schröter", "Schrötter", "Schubert", "Schukowski",
        "Schultz-Hencke", "Schumow", "Schumpeter", "Schur", "Schuster",
        "Schwabe", "Schwartz", "Schwarz", "Schwarzkopf", "Schwarzschild",
        "Schwehm", "Schweigger", "Schweikart", "Schwerd", "Scott",
        "Sealy", "Seaney", "Searle", "Sebastian", "Sébastien",
        "Second", "Secretary", "section", "see", "See",
        "Seebeck", "Seelman", "Seelmann-Eggebert", "Seely", "Sefström",
        "Segner", "Segre", "Seidel", "Seinfeld", "Seliwanow",
        "Sellmann", "Sellow", "Selwyn", "Selye", "Seminara",
        "Semmelweis", "Semple", "Sen", "Senefelder", "senior",
        "Serafin", "Seraji", "Sergejewitsch", "Serret", "Servais",
        "Seth", "Sewid", "Seykota", "S-H", "Shākir",
        "Shalom", "Shankar", "Shanks", "Shanlan", "Sharif",
        "Sheila", "Shermer", "Shettles", "Shetty", "Shihkao",
        "Shirazi", "Shonglin", "Short", "Shu-hua", "Shujā",
        "Shukla", "Shukor", "Shull", "Shuster", "Siacci",
        "Sibener", "Siddiqui", "Sidney", "Siegbahn", "Sigismund",
        "Sigmund", "Sijzi", "Sikelos", "Silberschlag", "Siliciano",
        "Sim", "Šimerka", "Simon", "Simonds",
        "Simpson", "Sina", "Singer", "Singh", "Sinsteden",
        "Sir", "Sirin", "Sixun", "Slobodkin", "Small",
        "Smith", "Smoluchowski", "Snell", "Śniadecki", "Sohncke",
        "Sokal", "Solander", "Soldner", "Solotarjow", "SOM",
        "Somerville", "Sommaja", "Sommer", "Sömmerring", "Song",
        "Sorby", "Soret", "Spallanzani", "Spangler", "Spann",
        "Sparks", "Spaun", "Spertzel", "Spiegelman", "Spottiswoode",
        "Sprengel", "Sr.", "St.", "Stäckel", "Stahl",
        "Stampfer", "Stan", "Stanfield", "Stanhope", "Stanley",
        "Stanton", "Starkey", "Starzl", "States", "Staude",
        "Staudt", "Stawell", "Stebbins", "Steere", "Stefan",
        "Steglich", "Steiner", "Steinheil", "Steinitz", "Steinmetz",
        "Stepanowitsch", "Stephan", "Stephen", "Stern", "Sternberg",
        "Stetter", "Steve", "Steven", "Stevens", "Stewart",
        "Stickelberger", "Stieltjes", "Stirling", "Stoecker", "Stokes",
        "Stoletow", "Stolz", "Stone", "Stoney", "Størmer",
        "Stott", "Stowell", "Stradonitz", "Streintz", "Stresemann",
        "Strouhal", "Strutt", "Stuart", "Study", "Stulić",
        "Sturgeon", "Sturm", "Styles", "Subbarao", "Subra",
        "Succow", "Sue", "Sufi", "Suleyman", "Sultan",
        "Summers", "Sung-Hou", "Superti-Furga", "Süring", "Suryal",
        "Svedberg", "Swami", "Swan", "Swarup", "Sweeney",
        "Swetnam", "Sydney", "Syed", "Sykes", "Sylow",
        "Sylvester", "Systems", "Szarvassi", "Szep", "T.",
        "Tabari", "Tabib", "Tabrizi", "Tahir", "Tait",
        "taken", "Tamimi", "Tammann", "Tank", "Tannery",
        "Tardieu", "Tāriq", "Taurinus", "Tawfik", "Taylor",
        "Taymiyyah", "Teixeira", "television", "Temple", "Templeton",
        "Ten", "Tenchini", "Tengmalm", "Terry", "Tesla",
        "Tessmann", "Tetrode", "th", "Thaer", "Thalén",
        "Thanikaimoni", "the", "The", "Theimer", "Theodor",
        "Theodore", "Theophilus", "Theorell", "Theoretical", "Thérèse",
        "Thessalonica", "Thévenot", "Thibaut", "Thiele", "Thiéry",
        "Thilorier", "Thirsk", "Thom", "Thomae", "Thomas",
        "Thompson", "Thomson", "Thon", "Thorp", "Thuan",
        "Thue", "Thuma", "Tiedjens", "Tietze", "Tillberg",
        "Tim", "Timberell", "time.", "Timothy", "Tinsley",
        "Tisserand", "to", "Tobias", "Todhunter", "Toepler",
        "Tolba", "Tolver", "Tommy", "Tordoff", "Torres",
        "Torricelli", "Tosti", "Townsend", "Tralles", "traveler",
        "Treadwell", "Trebizond", "Trentel", "Trésaguet", "Treviranus",
        "Triclinius", "Trist", "Trouton", "Trudel", "Truetttley",
        "Tryggvason", "Tschebyschow", "Tseng", "Tsien", "Tsou",
        "Tufail", "Tường", "Turk", "Turner", "Turowicz",
        "Turton", "Tusi", "Tuve", "Tuzo", "Tyndall",
        "ud-Din", "Ude", "ul", "Ulbricht", "ul-din",
        "Ulrich", "Umpfenbach", "Umpleby", "Underwood", "Unger",
        "United", "Upton", "Uqlidisi", "Urdi", "Usmani",
        "Uvarov", "uz-Zaman", "V.", "Vafa", "Vahlen",
        "Val", "Valier", "Vallisneri", "Valsamon", "van",
        "Van", "Varshney", "Vaschy", "Vatvat", "VC",
        "Veillon", "Veranzio", "Verdet", "Verhulst", "Vernon",
        "Veronese", "Verrier", "Verschaffelt", "Vessiot", "VI",
        "Victor", "Vidius", "Vieillot", "Vietoris", "VII",
        "Villard", "Violle", "Virchow", "Viskanta", "Visvesvaraya",
        "Vitullo", "vizier", "Vo-Dinh", "Voelkner", "Vogel",
        "Voigt", "Vokes", "Volkman", "Volkmer", "Vollmer",
        "Volterra", "voluminous", "vom", "von", "Vonderlinn",
        "Voss", "Vries", "Vryennios", "Vyzantinos", "Vyzantios",
        "W.", "Waals", "Wachter", "Wade", "Waetzmann",
        "Wafa", "Wagih", "Wagman", "Wagner", "Wagner-Jauregg",
        "Wahab", "Wai-Ling", "Waismann", "Walckenaer", "Wald",
        "Walenta", "Walfrid", "Walker", "Wallace", "Wallenberg",
        "Waltenhofen", "Walter", "Walton", "Waly", "Wang",
        "Wangerin", "Wani", "Wansink", "Wantzel", "Warburg",
        "Ward", "Warner", "Warwick", "Wassiljewna", "Waterston",
        "Watson", "Watt", "Wattenberg", "Wattenwyl", "Watzlawick",
        "Weber", "Webster", "Wegener", "Wehnelt", "Weibull",
        "Weierstraß", "Weihan", "Weingarten", "Weinhold", "Weininger",
        "Weir", "Weisbach", "Weiss", "Weisskopf", "Weiszmann",
        "Wei-zang", "Welbourn", "Welker", "Wellington", "Wells",
        "Welsbach", "Welskopf-Henrich", "Wen", "Wendell", "Wendt",
        "Wenhao", "Wenström", "Wentworth", "Wentzel", "Wenzhong",
        "Werbos", "West", "Westbrook", "Westphal", "Weyer",
        "Weyr", "Whalen", "Wheatstone", "Wheeler", "Whitbread",
        "White", "Whitlow", "Whitney", "Wickner", "Wicks",
        "Widdowson", "Widnall", "Wiedemann", "Wiegand", "Wieghardt",
        "Wien", "Wiener", "Wiese", "Wieser", "Wijthoff",
        "Wikipedia", "Wilbanks", "Wilbur", "Wild", "Wilder",
        "Wiley", "Wilfred", "Wilhelm", "Wilkins", "Wilkinson",
        "Willard", "William", "Willis", "Williston", "Willman",
        "Willson", "Wilson", "Wiltheiss", "Wilton", "Wiman",
        "Wingquist", "Winkelmann", "Winkelstein", "Winkler", "Winslow",
        "Winter", "Wise", "with", "Withers", "Wittgenstein",
        "Witting", "Wlassak", "Woese", "Wold", "Wolf",
        "Wolff", "Wolffgramm", "Wolfgang", "Wolfrum", "Wolfskehl",
        "Wollaston", "Wolstenholme", "Wong-Staal", "Wood",
        "Woodhouse", "Woodruff", "Woods", "Woodward", "Woolsey",
        "Wöpcke", "Woronoi", "Worpitzky", "Wratt", "Wright",
        "writers", "Wrobel", "Wróblewski", "Wronski", "wrote",
        "Wu", "Wüllner", "Wurman", "Würschmitt", "Wushmgir",
        "Wybe", "X.", "Xaver", "Xianghua", "Xiantu",
        "Xiaogang", "Xijin", "Ximing", "Xing",
        "Xitao", "Xuan", "Xuejing", "Y.", "Yafeng",
        "Yang", "Yaruss", "Yazami", "Yazdi", "Yazid",
        "Yeates", "Yener", "Yeo", "Yingxing", "Yize",
        "Yockey", "Yogore", "Yongzhi", "You", "Young",
        "Yousaf", "Yu", "Yuen", "Yuhanna", "Yunus",
        "Yusef", "Yusuf", "Yūsuf", "Yves", "Z.",
        "Zacharias", "Zāda", "Zadeh", "Zahn", "Zahran",
        "Zahrawi", "Zakerian", "Zamboni", "Zamecnik", "Zantedeschi",
        "Zayn", "Zehnder", "Zeilinger", "Zeller", "Zeuthen",
        "Zevelinos", "Zewail", "Zhan", "Zhen", "Zhengtang",
        "Zhongcheng", "Zhongjian", "Zhongli", "Zhou", "Ziaur",
        "Zijerdi", "Zillmer", "Zillur", "Zindel", "Zindler",
        "Zippe", "Ziyuan", "Zoch", "Zöllner", "Zonaras",
        "zoologist", "Zöppritz", "Zoretti", "Zsigmondy", "Zuberbier",
        "Zuckermandel", "Zuhr", "Zülicke", "Zwicker", "اخوان",
        "الصفا", "الوفا", "وخلان"};
    
    /**
     * Generate a random nickname consisting of firstname, a possible middle part and a lastname. They are separated using the given separator.
     * Does not respect length limitation of nicknames. You need to repeat calling this function until {@link Identity#validateNickname(String)} does not throw.
     */
    static private String newNameBaseUnlimitedLength(String seperator) {
        Random rand = new Random();
        StringBuilder name = new StringBuilder(Identity.MAX_NICKNAME_LENGTH);
        String previousPart = firstnames[rand.nextInt(firstnames.length)];
        name.append(previousPart);
        
        do {
			name.append(seperator);
			previousPart = lastnames[rand.nextInt(lastnames.length)];
			name.append(previousPart);
			
			// Append nameparts as long as the last part is either not sensible or you roll 1 on a
			// die :)
		} while (
			previousPart.endsWith(".") ||  // middle name
			previousPart.equals("ibn") ||  // "son of"
			previousPart.equals("al") ||   // Arabic prefix for "the"
			previousPart.length() == 1 ||  // just 1 letter
			rand.nextInt(6) == 1           // roll a die
		);
		
        return name.toString();
    };
    
    static private String newNameBase(String separator) {
    	String name;
		boolean invalidName = true;
    	
    	byte iterations = 0;
    	
    	do {
    		name = newNameBaseUnlimitedLength(separator);
    		try {
    			Identity.validateNickname(name);
    			invalidName = false;
    		} catch(InvalidParameterException e) {}
    		
    		assert(++iterations < 10);
    	} while(invalidName);
    	
    	return name;
    }

    /** Generate a Nickname: No spaces. */
    static public String newNickname() {
        return newNameBase("_");
    };

}
