#!/bin/bash
set -o nounset
set -o errexit
set -o errtrace
trap 'echo "Error at line $LINENO, exit code $?" >&2' ERR

tmpdir="$(mktemp --directory)"
trap 'rm -rf -- "$tmpdir"' EXIT

from_ant="$(mktemp --tmpdir="$tmpdir" --directory --suffix=.from-ant)"
from_gradle="$(mktemp --tmpdir="$tmpdir" --directory --suffix=.from-gradle)"

echo "Building with Ant..."
gradle clean &> /dev/null
ant -Dtest.skip=true clean dist &> /dev/null

echo "Building with Gradle..."
ant clean &> /dev/null
gradle clean jar testJar &> /dev/null

# To test whether the diff fails if it should:
#echo a >> "$from_gradle/plugins/WebOfTrust/WebOfTrust.class"

echo "Diffing:"
echo "Ant output:    $from_ant"
echo "Gradle output: $from_gradle"
if diff --recursive "$from_ant" "$from_gradle" ; then
	echo "JARs are identical!"
	exit 0
else
	echo "JARs do not match! Not deleting output so you can inspect it." >&2
	trap - EXIT
	exit 1
fi
