#!/bin/bash

if [ ! -e dist/WebOfTrust.jar ] && [ -e ../dist/WebOfTrust.jar ] ; then
	cd ..
fi

java -Xmx1024M  -classpath ../fred/lib/bcprov.jar:../fred/lib/freenet/freenet-ext.jar:../fred/dist/freenet.jar:dist/WebOfTrust.jar plugins.WebOfTrust.ui.terminal.WOTUtil "$@"
